import myFunc

x = myFunc.calcSum(1,2)

if x != 3:
  print("Test failed!")
  exit(1)
else:
  print("Test passed!")
